### ISSUE TITLE
README.md wrong?

### ISSUE THREAD

**Issue by drpowell** [biotool-paper/biotool#11]
Looks like the TOTAL and NUMSEQ columns are swapped in all the examples?

**Comment by bjpop** [comment]
Yes, I agree. The README is incorrect (and I just noticed the Haskell and Python versions are incorrect in the same way). Maybe we can come up with better names for the column headings?

**Comment by bjpop** [comment]
Corrected the TOTAL and NUMSEQ ordering in the README.md in 0899e6c54d9a05a47bf1df13fee9027e8e7210d0
