### ISSUE TITLE
Bug in Perl code (and perhaps others): minlen can cause the program to claim input file is not FASTA if there are 0 reads greater than the minimum length

### ISSUE THREAD

**Issue by bjpop** [biotool-paper/biotool#13]
When minlen causes 0 reads to be counted the program claims the input is not FASTA:

$ ./biotool.pl --minlen 1000 ../test_data/*
FILENAME	TOTAL	NUMSEQ	MIN	AVG	MAX
Skipping ../test_data/empty_file - doesn't seem to be FASTA?
Skipping ../test_data/one_sequence.fasta - doesn't seem to be FASTA?
Skipping ../test_data/two_sequence.fasta - doesn't seem to be FASTA?

I haven't tested all the other implementations, but something to watch out for.

**Comment by tseemann** [comment]
Fixed!
