### ISSUE TITLE
JS does not return correct exit status on command line error

### ISSUE THREAD

**Issue by bjpop** [biotool-paper/biotool#25]
According to our README.md, biotool should return an exit status of 2 when there is a command line argument error.

The JS implementation returns an exit status of 0 when given the argument:

```
--this_is_not_a_valid_argument
```

This is causing the JS library to fail on a travis test.

**Comment by bjpop** [comment]
Likewise for the Ruby implementation.

**Comment by drpowell** [comment]
Fixed  - and tests enabled
