### ISSUE TITLE
Package up Perl code?

### ISSUE THREAD

**Issue by bjpop** [biotool-paper/biotool#3]
Hi Torsten,

I tried to run the Perl code, but I don't have the necessary Bio library installed on my computer.

Is there a way to package up the perl code so that it will download the necessary dependencies, preferably into a local package database? Similar to pip, or the stack tool in Haskell?

**Comment by tseemann** [comment]
It kind of is possible with FatPacker but BioPerl is gigantic.  Usually expect user to install it via cpan: `cpan Bio::Perl`  . Not sure if @drpowell is bundling all the npm stuff?

**Comment by drpowell** [comment]
I think instructions in a readme for the directory to run something like `cpan -i Bio::Perl` is enough.  That's what haskell, ruby & js have so far

**Comment by bjpop** [comment]
Actually it is a bit more than that.

For Haskell and Python at least there is infrastructure to install the code onto the system, either locally in a sandbox or globally.

**Comment by tseemann** [comment]
@bjpop you can install to local with cpan too using `local::lib` similar to `pip --user`

**Comment by bjpop** [comment]
Will that install the dependencies as well?

Can you please show the full cpan command that will install your biotool plus its dependencies in some local place? Doesn't have to be in the $PATH.

Cheers
Bernie

**Comment by tseemann** [comment]
I have now fixed this by creating a README.md in the perl5 folder which explains how to install BIoperl for Debian, Redhat and General Unix via CPAN.
