### ISSUE TITLE
Make it more useful

### ISSUE THREAD

**Issue by Slugger70** [biotool-paper/biotool#38]
I know these are only meant to be templates for good programming practices but could we make the scripts a bit more useful by making them calculate things like GC content, n50 and number of Ns? Then the code would be much more useful in itself.

**Comment by tseemann** [comment]
That is unlikely to happen. The specs were defined a while ago and much work has gone into now. We are trying to finish up the project.

**Comment by bjpop** [comment]
A good idea, but beyond the scope at the moment.
