### ISSUE TITLE
Rounding differences in languages when computing average sequence length

### ISSUE THREAD

**Issue by bjpop** [biotool-paper/biotool#4]
I noticed a difference in the average output between the Haskell and Python implementations.

Haskell:
round 0.5 == 0

Python 2.7:
round(0.5) == 1.0

Python 3.3:
round(0.5) == 0

This will have consequences for the output of our programs, if we compare them for computing exactly the same answer.

Should we standardise on the output?

**Comment by drpowell** [comment]
Ugh, never realised how inconsistent round() was implemented.  I suggest we go with floor() which is close enough for this and at least consistent!

**Comment by bjpop** [comment]
Ok, let's use floor. Must remember to note this behaviour in the documentation.
