### ISSUE TITLE
Check that renaming directories and files in biotool-boot.sh is safe and does not clash with existing names

### ISSUE THREAD

**Issue by bjpop** [biotool-paper/biotool#46]
In biotool-boot.sh we rename any files or directories in the source tree that might contain the word "biotool" and replace it with whatever the new project is called.

However, during this renaming, I don't think that we check whether a file already exists with the new name. This is extremely unlikely, but still possible. We should check for this and abort the program if it occurs. 

Perhaps the simplest way to do this is to check the exit status of the mv command?

**Comment by supernifty** [comment]
If a file or directory can't be renamed, biotool-boot.sh aborts with a suggestion to choose a different project name.
