### ISSUE TITLE
Consistent handling of empty files

### ISSUE THREAD

**Issue by drpowell** [biotool-paper/biotool#7]
What is the expected behaviour on files with no sequences?

Currently the perl impl prints to stderr :  "Skipping $file - doesn't seem to be FASTA?\n";
The haskell version silently skips.

**Comment by tseemann** [comment]
This issue is now resolved in the documentation it seems.

It should behave like a file which results in 0 sequences after filtering:

```
file.fa  0  0  -  -  -
```
